version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - '3001:3000'
    image: app:react
    container_name: react_container
    command: npm start


